name: Rebuild
on:
  #pull_request:
  push:
  #workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    container:
      image: docker://registry.fedoraproject.org/fedora:33
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Lilypond
        run: |
          sudo dnf -y install lilypond
      - name: Build main files
        run: |
          lilypond *.ly
      - name: Upload main files (1)
        uses: actions/upload-artifact@v2
        with:
          name: 'Doprovodník'
          path: doprovodník.pdf
      - name: Upload main files (2)
        uses: actions/upload-artifact@v2
        with:
          name: 'Zpěvník'
          path: zpěvník.pdf
      - name: Build all partial files
        run: |
          for file in ./**/*.ly ; do
            lilypond "$file" || echo "Failed to build $file"
          done
      - name: Upload partial files
        uses: actions/upload-artifact@v2
        with:
          name: 'Jednotlivé písně'
          path: '**/*.pdf'
