name: Rebuild
on:
  #pull_request:
  push:
  #workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    env:
      CONTAINER: 'docker://registry.fedoraproject.org/fedora:36'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Write script
        run: |
          #touch build.sh
          << EOF > build.sh
          set -eu
          sudo dnf -y install lilypond
          cd /komunitni-noty
          for file in ./**/*.ly ; do
            lilypond "$file" || echo "Failed to build $file"
          done
          EOF
          chmod +x build.sh
      - name: Run script in the container
        run: |
          podman run -v `pwd`:/komunitni-noty ${{ env.CONTAINER }} bash /komunitni-noty/build.sh
      - name: Upload main files (1)
        uses: actions/upload-artifact@v2
        with:
          name: 'Doprovodník'
          path: doprovodník.pdf
      - name: Upload main files (2)
        uses: actions/upload-artifact@v2
        with:
          name: 'Zpěvník'
          path: zpěvník.pdf
      - name: Upload partial files
        uses: actions/upload-artifact@v2
        with:
          name: 'Jednotlivé písně'
          path: '**/*.pdf'
